apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 10-mysql.yaml
  - 20-backend.yaml
  - 30-frontend.yaml
  - 40-autoscaling.yaml
  - 50-security.yaml
  - 60-prometheus.yaml
  - 61-grafana.yaml
  - 70-backups.yaml
images:
  - name: skillpulse-backend
    newName: haideralimazari/skillpulse-backend
    newTag: cc05e8294a7589e43e7d48d0556a4fb3b2fee9a7
  - name: skillpulse-frontend
    newName: haideralimazari/skillpulse-frontend
    newTag: cc05e8294a7589e43e7d48d0556a4fb3b2fee9a7
